name:                ENIG
version:             0.0.0.2
github:              "QuietJoon/ENIG"
license:             BSD3
author:              "YongJoon Joe"
maintainer:          "developer+ENIG@quietjoon.net"
copyright:           "2016-2019 YongJoon Joe"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Auto Korean conjugator/adjustor/adopter/converter
category:            Natural Language Processing

description:         Please see the README on GitHub at <https://github.com/QuietJoon/ENIG#readme>

library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5
  - text
  - vector
  - unicode-transforms

tests:
  ENIG-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
    - TemplateHaskell
    dependencies:
    - ENIG
    - HUnit
    - QuickCheck
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2
    - test-framework-th
    - base
    - text
    - unicode-transforms
